### ISSUE TITLE
what is gulp task for?

### ISSUE THREAD

**Issue by LeiZeng** [yumaoywj/super-ginger#1]
@yumaoywj 
I try to build the code with your gulp task, but it turns out never use the built code, do you think what is the gulp task for?

P.S. I forked your repo and publish a `gh-pages` to share with my friend, they love it very much, big thanks for you fantastic work. 

https://github.com/LeiZeng/super-ginger 
demo: http://leizeng.github.io/super-ginger

**Comment by devyumao** [comment]
Hi，@LeiZeng

Thank you for your support!

The gulp task is for generating a distribution version which is running in WeChat. In `dist`, there are some php files which contain private code such as the WeChat open ID, so I removed the folder. 

You can experience Super Gingy's full functionality (multiple heroes, store, ranking) in your WeChat by scanning the QR code below.

![QR code](https://raw.githubusercontent.com/yumaoywj/super-ginger/master/src/img/qr.png)
